# fly.toml app configuration file generated for ralph-storefront on 2024-04-09T12:51:47+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ralph-storefront'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile.fly'

[build.args]
  API_ENDPOINT='https://merchantapi.geins.io/graphql'
  API_KEY='CF2FF80B-6F85-4CD9-ACE5-F41962891E07'
  AUTH_ENDPOINT='https://car-auth-fa-prod.azurewebsites.net/api/demogeins_prod/'
  BASE_URL='https://ralph-storefront.fly.dev'
  DEFAULT_LOCALE='sv'
  FALLBACK_CHANNEL_ID='1|se'
  FALLBACK_MARKET_ALIAS='se'
  IMAGE_SERVER='https://demogeins.commerce.services'
  RALPH_ENV='prod'
  SIGN_ENDPOINT='https://merchantapi.geins.io/auth/sign/{API_KEY}?identity='

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
