name: Deploy to Fly.io and Lighthouse audit
on:
  push:
    branches:
      - master
jobs:
  fly:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg API_KEY=${{ secrets.API_KEY }} --build-arg RALPH_ENV=prod
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  lighthouse:
    needs: fly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://ralph-storefront.fly.dev/se/sv
            https://ralph-storefront.fly.dev/se/sv/l/kampanjprodukter/third-level
            https://ralph-storefront.fly.dev/se/sv/p/gavor-2/foretagsgavor-2/guldpraliner-24-karat-2
          uploadArtifacts: true
          temporaryPublicStorage: true
