name: Deploy to Fly.io
on:
  push:
    branches:
      - master
jobs:
  fly:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg API_KEY=${{ secrets.API_KEY }} --build-arg RALPH_ENV=prod
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
